CREATE TABLE IF NOT EXISTS Users(
  ID INTEGER PRIMARY KEY NOT NULL,
  USERNAME TEXT NOT NULL,
  PASSWORD TEXT NOT NULL,
  EMAIL TEXT NOT NULL,
  ASSET_NAME TEXT,
);

CREATE TABLE IF NOT EXISTS Sessions(
  ID INTEGER PRIMARY KEY NOT NULL,
  SESSION_COOKIE TEXT NOT NULL,
  CHALLENGE TEXT NOT NULL,
  PUBKEY TEXT,
  DIRTREE NONE,
  FILES NONE,
  TIMESTAMP_LAST INT NOT NULL
);