CREATE TABLE IF NOT EXISTS Sessions(
  ID INTEGER PRIMARY KEY NOT NULL,
  SESSION_COOKIE TEXT NOT NULL,
  CHALLENGE TEXT NOT NULL,
  PUBKEY TEXT,
  DIRTREE NONE,
  FILES NONE,
  TIMESTAMP_LAST INT NOT NULL
)